# Generated by Django 5.2.8 on 2025-11-06 13:22

import datetime
import django.db.models.deletion
import gestion.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_access', models.BooleanField(default=False, verbose_name='Acceso QR')),
                ('inactive', models.BooleanField(default=False, verbose_name='Desactivado')),
                ('code', models.CharField(default='', max_length=200, verbose_name='Code')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Razón Social')),
                ('phone', models.CharField(default='0000000000', max_length=50, null=True, verbose_name='Teléfono de contacto')),
                ('email', models.EmailField(default='', max_length=254, null=True, verbose_name='Email de contacto')),
                ('address', models.TextField(default='', null=True, verbose_name='Dirección')),
                ('observations', models.TextField(default='', null=True, verbose_name='Observaciones')),
                ('qr', models.ImageField(blank=True, help_text='Select file to upload', upload_to=gestion.models.upload_form_qr, verbose_name='QR')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Razón Social')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(default='', max_length=20, verbose_name='PIN')),
                ('dni', models.CharField(default='', max_length=20, verbose_name='DNI')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Razón Social')),
                ('phone', models.CharField(default='0000000000', max_length=50, null=True, verbose_name='Teléfono de contacto')),
                ('email', models.EmailField(default='', max_length=254, null=True, verbose_name='Email de contacto')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='gestion.zone', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=0, verbose_name='Día')),
                ('ini', models.TimeField(default=datetime.time(8, 0), max_length=10, verbose_name='Hora de inicio')),
                ('end', models.TimeField(default=datetime.time(8, 0), max_length=10, verbose_name='Hora de fin')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetables', to='gestion.client', verbose_name='Cliente')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetables', to='gestion.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish', models.BooleanField(default=False, verbose_name='Terminada')),
                ('ini_date', models.DateTimeField(default=datetime.datetime(2025, 11, 6, 13, 22, 14, 188051), null=True, verbose_name='Inicio')),
                ('end_date', models.DateTimeField(default=datetime.datetime(2025, 11, 6, 13, 22, 14, 188075), null=True, verbose_name='Fin')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistances', to='gestion.client', verbose_name='Client')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistances', to='gestion.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed', models.BooleanField(default=False, verbose_name='Estado')),
                ('code', models.CharField(max_length=10, verbose_name='Código')),
                ('subject', models.CharField(max_length=255, verbose_name='Asunto')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Descripción')),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2025, 11, 6, 13, 22, 14, 188795), verbose_name='Creado el')),
                ('closed_date', models.DateTimeField(blank=True, default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999), null=True, verbose_name='Cerrado el')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'ordering': ['-creation_date'],
            },
        ),
    ]
