# Generated by Django 5.2.8 on 2025-11-10 09:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=50, verbose_name='Código')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=50, verbose_name='Código')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de servicio',
                'verbose_name_plural': 'Tipos de servicios',
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='zone',
        ),
        migrations.AlterField(
            model_name='incident',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 10, 9, 50, 53, 387646), verbose_name='Creado el'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, null=True, verbose_name='Borrado')),
                ('ini_date', models.DateTimeField(default=datetime.datetime(2025, 11, 10, 9, 50, 53, 386659), null=True, verbose_name='Inicio')),
                ('end_date', models.DateTimeField(default=datetime.datetime(2025, 11, 10, 9, 50, 53, 386685), null=True, verbose_name='Fin')),
                ('place_notes', models.TextField(default='', null=True, verbose_name='Notas')),
                ('clean_notes', models.TextField(default='', null=True, verbose_name='Notas del empleado')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='gestion.client', verbose_name='Cliente')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='gestion.employee', verbose_name='Empleado')),
                ('infestation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.infestation', verbose_name='Agente a combatir')),
                ('service_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.servicetype', verbose_name='Tipo de servicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.DeleteModel(
            name='Assistance',
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
